---
name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4
    - run: make test
    - run: make pre-commit
